# Generated by Django 5.1.3 on 2024-11-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=200)),
                ('std_class', models.CharField(max_length=50)),
                ('std_age', models.CharField(max_length=50)),
                ('std_phone', models.IntegerField()),
            ],
        ),
    ]
